Repository liberland/liberland_substrate, pull requests merged in 2022-11, with the labels that each got.

#113 Legislation pallet fixes
  Cargo.lock
  bin/node/cli/Cargo.toml
  bin/node/runtime/Cargo.toml
  bin/node/runtime/src/lib.rs
  frame/democracy/src/lib.rs
  frame/liberland-legislation/src/lib.rs
  frame/llm/src/lib.rs
Labels: A0-pleasereview, feedback given

#131 change senate key, modifications for Hazlitt, reorder chain spec files
  README.md
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/src/lib.rs
  customSpec.json
  customSpecRaw.json
  frame/llm/src/lib.rs
  liberland-menger.json
  specs/hazlitt.json
  specs/hazlittRaw.json
  specs/readme.md
Labels: A0-pleasereview

#122 Update docs on running validator + helper scripts for generating keys
  docs/liberland/how_to_run_validator.md
  scripts/generate_stored_keys.sh
  scripts/insert_keys_gen.sh
Labels: documentation, A0-pleasereview

#124 Helper script for granting Liberland citizenships to dev accounts
  scripts/setup-dev-testnet.sh
Labels: documentation, A0-pleasereview

#146 Remove obsolete FIXME comments from code
  frame/democracy/src/lib.rs
  frame/elections-phragmen/src/lib.rs
Labels: A0-pleasereview

#153 Election switch
  bin/node/cli/src/chain_spec.rs
  bin/node/runtime/src/constants.rs
  bin/node/runtime/src/lib.rs
Labels: A0-pleasereview
